### ISSUE TITLE
Explain how to use notebooks in various settings

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/sample.starter_notebooks#1]
Notebooks show submitting from ICP4D - need to either be updated with instructions on how to use elsewhere (vanilla Streams + Jupyter, Watson Studio, or Jupyter + Streaming analytics) or modified so the notebook will figure out how to submit.

**Comment by rnostream** [comment]
When running Jupyter locally the notebooks need to have set the cfg variable as empty `cfg ={}`. Topology takes than the environment variables (as described by topology). I use this approach for developing the notebooks with my local  (vanilla) Streams.

Explaining the different configurations and necessary environment variables is a longer part and should not be done in every notebook but separately. 

But before adding further effort on this, I think we should come to a clear understanding what role notebooks should play for a user in future.

**Comment by ddebrunner** [comment]
One issue is that for ICP4D we want to use Python 3.6 features (such as typed tuples for schema definition) but those will not work on Streaming Analytics since it is currently using 3.5.

**Comment by natashadsilva** [comment]
I started with the Rolling average sample to make it reusable in various contexts.
Option 1: Include all instructions within the notebook - keeps it all in one place but makes the notebook long and easy to get confused
https://github.com/IBMStreams/sample.starter_notebooks/blob/doc_update/Streams-RollingAverageSample.ipynb
Option 2: Documented in one place, notebook is shorter but downside is it isn't self contained:
https://github.com/IBMStreams/sample.starter_notebooks/blob/doc_update/Streams-RollingAverageSample-InstructionsOnly.ipynb

**Comment by markheger** [comment]
@natashadsilva I would prefer option 2, with the `Auth-Instructions.md` hosted externally and keep the notebooks shorter with the default for CP4D (inside a project).

**Comment by ddebrunner** [comment]
@natashadsilva
> STREAMS_BUILD_URL = "https://9.114.60.161:30587/streams/rest/builds"

Only this is needed (and matches your instructions):

`STREAMS_BUILD_URL = "https://9.114.60.161:30587"`

**Comment by ddebrunner** [comment]
@natashadsilva The streaming analytics public cloud can be simplified to use just the credentials using: `ConfigParams.SERVICE_DEFINITION`

https://streamsxtopology.readthedocs.io/en/latest/streamsx.topology.context.html#streamsx.topology.context.ConfigParams.SERVICE_DEFINITION

**Comment by ddebrunner** [comment]
@natashadsilva Having the service instance name be more meaningful would be good, instead of `anaconda-patch-3` :-)

**Comment by natashadsilva** [comment]
> @natashadsilva
> 
> > STREAMS_BUILD_URL = "https://9.114.60.161:30587/streams/rest/builds"
> 
> Only this is needed (and matches your instructions):
> 
> `STREAMS_BUILD_URL = "https://9.114.60.161:30587"`

@ddebrunner are you referring to this section:
https://gist.github.com/natashadsilva/bf1658698d245ef6d03778ed87886034#edge?

It's based on what's here under "IBM Cloud Pak for Data standalone"

**Comment by ddebrunner** [comment]
@natashadsilva Yes, section 1.1.2, which yesterday had the required STREAMS_BUILD_URL, but now the section has dropped the instructions for STREAMS_BUILD_URL, but STREAMS_BUILD_URL is required.

**Comment by natashadsilva** [comment]
Instructions are here:
http://ibmstreams.github.io/streamsx.documentation/docs/python/1.6/python-appapi-devguide-3/#1-set-up-a-connection-to-the-streams-instance
