### ISSUE TITLE
Streams-HdfsSample notebook has to support GenericWebHDFS connection

### ISSUE THREAD

**Issue by anouri** [IBMStreams/sample.starter_notebooks#43]
The GenericWebHDFS connection in CP4D generates a python dictionary with the following properties:
- username
- password
- url (generic attribute) 

The pypi.stremsx.hdfs needs the following attributes in a JSON string:
```
{
    "user": "hdfs-user-name",
    "password": "hdfs-password",
    "webhdfs": "webhdfs://hdfs-hostname:wenhdfs-port"
}
```

The Streams-HdfsSample notebook has to convert the generated properties to a suitable JSON string for pypi.stremsx.hdfs.
username -> user 
and url -> webhdfs

**Comment by markheger** [comment]
better to support the "GenericWebHDFS connection" dict in pypi.stremsx.hdfs as credentials parameter. Keeps the notebook code (user code) simpler.

**Comment by anouri** [comment]
The solution will be delivered in `pypi.streamsx.hdfs`

https://github.com/IBMStreams/pypi.streamsx.hdfs/issues/11

**Comment by anouri** [comment]
The HDFS notebook has now tow options to put the webhdfs credentials:
- 1- Copy the credentials JSON string in the clipboard and paste it into `getpass` field.
- 2- Crete an external configuration from type `GenericWebHDFS` and put the connection name as HDFS credentials.
