### ISSUE TITLE
Changes required in Notebooks to work with EventStore v2.0.0.5 on CP4Dv3.0.1

### ISSUE THREAD

**Issue by gigglegrig** [IBMStreams/sample.starter_notebooks#55]
With the changes made in EventStore v2.0.0.5 deployment, we need some changes in the 
notebook (when the notebooks is checkout to CP4D-3.0.1 branch):

1/ Step 1.3:
![image](https://user-images.githubusercontent.com/26666987/83773691-db992f80-a652-11ea-8c4d-9356e6eee79b.png)
Suggestion: include an example for `host`, for example: `zen-cpd-zen.apps.cpd-001-lb-1.fyre.ibm.com`

2/ Step 1.3.1 change to `eventstore_metadata`
`clientkeystore = '/user-home/_global_/dbdrivers/eventstore_metadata/'+deployment_id+'/clientkeystore'`

This Only applies in EventStore v2.0.0.5 on CP4D V3.0.1.

3/ Step 1.3.1: in `rest_url` the `\nbg` in the path should be the CP4D project name, we should have an variable for user to fill in, or read from the current project information.
![image](https://user-images.githubusercontent.com/26666987/83774363-9a554f80-a653-11ea-89bc-b924a51fec98.png)

This Only applies in all EventStore versions on CP4D.

**Comment by markheger** [comment]
notebook and python package need to be updated
