### ISSUE TITLE
latest branch does not have latest notebooks

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/sample.starter_notebooks#62]
Should develop branch be the default instead?

**Comment by markheger** [comment]
The develop branch can contain notebooks that are valid for upcoming releases only.
After new CPD version has been released the develop branch should be merged to latest branch.
Seems that this merge was missed after June release.

**Comment by markheger** [comment]
changes for CPD3.0.1 have been merged
develop = latest = CP4D-3.0.0.0 (since link in Streams service description points to CP4D-3.0.0.0, even in 3.0.1 release)
