### ISSUE TITLE
incomplete sentence in Timeseries notebook

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/sample.starter_notebooks#88]
The notebook section 2.3 has this:
> 2.3 Define a data source as a composite
>Composite transforms encapsulate multiple stream transforms in a single class and can be used as .....?.

I would fill it in myself, but I am not sure what the rest of the sentence ought to say.

**Comment by ghost** [comment]
My suggestion:

Composite transforms encapsulate multiple stream transforms in a single class for hiding complexity and re-use.
